version: '3.1'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    tty: true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $PWD/data/mysql/etc/my.cnf:/etc/mysql/my.cnf:ro
      - $PWD/data/mysql/data:/var/lib/mysql      
    restart: always
    command: [
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci",
      "--innodb_flush_log_at_trx_commit=1",
      "--sync_binlog=1"
      ]
    environment:
      MYSQL_ROOT_PASSWORD: 12wsxCDE#
      MYSQL_DATABASE: teleport
      MYSQL_USER: teleport
      MYSQL_PASSWORD: 12wsxCDE#
    ports:
      - 3306:3306
    restart: always

  teleport:
    build: .
    image: teleport:v3.3.1
    container_name: teleport
    tty: true
    depends_on:
      - mysql
    command: bash -c "/usr/local/teleport/start.sh && tail -f /usr/local/teleport/data/log/*.log"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $PWD/data/teleport/etc:/usr/local/teleport/data/etc
      - $PWD/data/teleport/replay:/usr/local/teleport/data/replay
      - $PWD/data/teleport/log:/usr/local/teleport/data/log 
    ports:
      - 7190:7190
      - 127.0.0.1:52080:52080
      - 52089:52089
      - 52189:52189
      - 52389:52389
    restart: always
  
  nginx:
    build: .
    image: nginx:latest
    container_name: nginx
    tty: true
    depends_on:
      - teleport
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $PWD/data/nginx/etc/nginx.conf:/etc/nginx/nginx.conf
      - $PWD/data/nginx/etc/conf.d:/etc/nginx/conf.d
      # - /NWJXZ:/NWJXZ
      # - /opt/nginx/html:/opt/nginx/html
      - $PWD/data/nginx/html:/opt/nginx/html
      - /var/log/nginx:/var/log/nginx
    ports:
       - 8000:80
       - 8080:8080
    restart: always

  haproxy:
     image: haproxy
     container_name: haproxy
     tty: true
     volumes:
       - $PWD/data/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
     depends_on:
       - nginx
     ports:
       - "80:80"
     restart: always

  keepalived:
    image: osixia/keepalived:2.0.19 
    container_name: keepalived
    tty: true
    depends_on:
      - nginx
    network_mode: "host"
    #pid: "host"
    #pid: "container:nginx"
    pid: "service:nginx"
    cap_drop:
      - NET_ADMIN
    privileged: true
    volumes:
      - $PWD/data/keepalived/keepalived.conf:/usr/local/etc/keepalived/keepalived.conf:ro
      - $PWD/data/keepalived/nginx_check.sh:/container/service/keepalived/assets/nginx_check.sh:ro
    restart: always
    